### ISSUE TITLE
Error missing file for log activities

### ISSUE THREAD

**Issue by dcialdella** [toolsprods/SniffVPN#2]
---

 .' ____ \         (_) .' ..].' ..|_  _| |_  _|_   __ |_   |_   _|
 | (___ _|_ .--.  __ _| |_ _| |_   \ \   / /   | |**) ||   \ | |
  _.__**`.[`.-. |[  '-| |-'-| |-'   \ \ / /    |  **_/ | |\ | |
 | _**_) || | | | | | | |   | |      \ ' /    _| |_   _| |_\   |_
  ______.[___||__[**_[**_] [**_]      \_/    |___**| |_____|____|

[---]         SniffVPN - Traffic monitor for your VPN          [---]
[---]          Created by: Alvaro Nunez (toolsprods)           [---]
[---]                     Version: 0.1                         [---]
[---]                Codename: 'Alfa Version'                  [---]
[---]        Follow me on GitHub: github.com/toolsprods/       [---]

[_] Running server at 10.8.0.1:8000...
[_] Can see statics and logs at 10.8.0.1:8000/panel

10.8.0.1 - - [05/Jul/2016 20:15:06] "GET /panel HTTP/1.1" 301 -
10.8.0.1 - - [05/Jul/2016 20:15:06] "GET /panel/ HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:15:06] "GET /panel/css/theme.css HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:15:07] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:07] "GET /favicon.ico HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:07] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:07] "GET /favicon.ico HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:16] "GET /panel/js/functions.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:15:16] "GET /panel/js/jquery.bootpag.min.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:15:17] "GET /panel/css/helveticaneue.woff HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:15:17] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:17] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:17] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:17] "GET /panel/data/logs.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:17] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:17] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:22] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:22] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:25] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:25] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:15:27] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:15:27] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:23:44] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:23:44] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
10.8.0.1 - - [05/Jul/2016 20:23:45] code 404, message File not found
10.8.0.1 - - [05/Jul/2016 20:23:45] "GET /panel/data/vtanalyzer.json HTTP/1.1" 404 -
Traceback (most recent call last):
  File "SniffVPN.py", line 113, in <module>
    main()
  File "SniffVPN.py", line 109, in main
    sniff(iface=interface, prn=packet, count=count)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "SniffVPN.py", line 79, in packet
    iporig=getOriginalIP(ipsrc)
  File "SniffVPN.py", line 89, in getOriginalIP
    file=open('/var/log/openvpn-status.log','r')
**IOError: [Errno 2] No such file or directory: '/var/log/openvpn-status.log'**

**Comment by toolsprods** [comment]
Hi dcialdella,

thanks for the report. It seems that not find the file _“/var/log/openvpn-status.log”_. This file is generated by the OpenVPN and has the record of public IP that connect through it.

Errors _"File not found"_ is because it has not generated files yet so it cannot be displayed on the web panel. Have you caught any HTTP GET request?

Greetings.

**Comment by dcialdella** [comment]
I created the file and give permissions..... but another error appears.

**Comment by dcialdella** [comment]
When I fixed files, permissions.... the log is this.

10.8.0.1 - - [05/Jul/2016 20:58:13] "GET /panel/ HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:14] "GET /panel/css/theme.css HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:14] "GET /panel/js/functions.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:14] "GET /panel/js/jquery.bootpag.min.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:14] "GET /panel/data/vtanalyzer.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:14] "GET /panel/data/logs.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:14] "GET /panel/data/logs.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:15] "GET /panel/data/logs.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:18] "GET /panel/data/logs.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:19] "GET /panel/data/vtanalyzer.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:20] "GET /panel/data/logs.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:21] "GET /panel/ HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:22] "GET /panel/css/theme.css HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:22] "GET /panel/js/functions.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:22] "GET /panel/js/jquery.bootpag.min.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:22] "GET /panel/data/vtanalyzer.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 20:58:22] "GET /panel/data/logs.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 21:02:43] "GET /panel/ HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 21:02:43] "GET /panel/css/theme.css HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 21:02:43] "GET /panel/js/functions.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 21:02:43] "GET /panel/js/jquery.bootpag.min.js HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 21:02:44] "GET /panel/data/vtanalyzer.json HTTP/1.1" 200 -
10.8.0.1 - - [05/Jul/2016 21:02:44] "GET /panel/data/logs.json HTTP/1.1" 200 -

**Comment by toolsprods** [comment]
Files you've created are blank?

**Comment by dcialdella** [comment]
yes. touch xxxxx

**Comment by toolsprods** [comment]
Hi, like #3 issue, this problem has already been solved.

You can check it with the new updates. If the error persists, please open a new issue.

Greetings.
