### ISSUE TITLE
Two files missing

### ISSUE THREAD

**Issue by dcialdella** [toolsprods/SniffVPN#3]
Two files seams missing in the folder /data

/panel/data/logs.json
/panel/data/vtanalyzer.json

or should be created....

**Comment by toolsprods** [comment]
Yes, these files are created the first time an HTTP request is captured. They are JSON files with a certain structure, so it is normal that creating these files by hand generated other errors.

The tool should automatically create files when it finds the requests.

**Comment by dcialdella** [comment]
Tomorrow I will review the code (Python) and suggest some changes.
I will verify it in Xubuntu.

**Comment by toolsprods** [comment]
Perfect. Let me know news.

Greetings.

**Comment by toolsprods** [comment]
Hi, this problem has already been solved.

You can check it with the new updates. If the error persists, please open a new issue.

Greetings.
